language: cpp
sudo: false
dist: xenial

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

env:
  global:
    - CTEST_OUTPUT_ON_FAILURE=1

  matrix:
    - CMAKE_BUILD_TYPE=Debug
    - CMAKE_BUILD_TYPE=Release

matrix:
  exclude:
    - os: linux
      compiler: clang
    - os: osx
      compiler: gcc

addons:
  apt:
    packages:
    - ninja-build
    - qtbase5-dev
    - gcc-5

before_install:
  - |
    # Install cmake and ninja
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      export QTDIR=/usr/lib/x86_64-linux-gnu/qt5
      export PATH="$QTDIR/bin:$PATH"
    else
      brew update > /dev/null
      brew tap homebrew/versions
      brew install ninja
      brew install qt
      export QTDIR="/usr/local/opt/qt5"
      export PATH="$QTDIR/bin:$PATH"
    fi

install:
  - |
    # Run cmake
    mkdir /tmp/build
    cd /tmp/build
    cmake -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE} ${TRAVIS_BUILD_DIR}

script:
  - cmake --build . --target cmakespark
  - cmake --build . --target runtests

deploy:
  provider: releases
  api_key:
    secure: PuJwafNV/FQYr9vQpVnvabbObtR5pnuKlyfSFRLUydMIQZ+XWPHGyv9AUFAY4juR0KRPJzztWyOZKnJdITCU11BPx93PGOCC8/6swRsWW5PFTIgTnH3H71bXX2WIVqgUY3UjPkEQY3xOyr+92tP62coOulyyAVXwdpFdlYEM/bDsSIvmRrT/ux9uGh/2Hnkxe5Cm1yykjdzI8vhTRvRcZIYLBysO6s+7Av6DJpysY2QxH2ibZkYp3fBNbyTyrkn76VOs/Phwc+a7bufDCVwGF3OWqDHFsP81OitSlBow0F292uK+ToFWC26XtrGFEvvWr5nKhj+1ZRE8/YbOnIvbxssWHcO+l5t8zCrNP3gkQLgyHRcNhCca4LJUwFOd564DqP9D+Jdc4dEvOCnr+U/fEvRJViPDkHglifU2weL6eED9Ex6yHt3lInzlrEvcsgLnvIlyKE8rLq7iMiZIeSJG8uK5+Mkd2HNOijOZq17r6qyqKoctbmDvkP+YbomZZPxYUKLCaORJ+eOdPej34+3eU/yO5ZZDN387ign2lLTZjsNT/oupN4S7C/oOfARZa4j/a+aFZssZLtI7qvBJO1Wubt7RN8WEiY3XDFuGKKwSubLF6CcEv2D7F2vcNes0eUUzHcCRpAKI9Dme1lTX6Xa44eWtGoI6mZlRreuMhF6GTSM=
  file: /tmp/build/cmakespark.zip
  overwrite: true
  on:
    tags: true

